FROM apache/airflow:2.10.5

USER root

# Optional: match host docker group if needed
RUN groupadd -g 999 docker && usermod -aG docker airflow


USER airflow

# Install Python dependencies permanently
RUN pip install --no-cache-dir \
    pyspark==4.0.0 \
    boto3 \
    minio \
    psycopg2-binary \
    apache-airflow-providers-apache-spark

USER root